# Generate LICENSE Workflow Configuration
name: generate-license
description: "Gera arquivo LICENSE com copyright da Embrapa automaticamente"
author: "BMad Embrapa I/O Module"

# Critical variables from config_source
config_source: "{project-root}/bmad/embrapa-io/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Workflow paths
installed_path: "{project-root}/bmad/embrapa-io/workflows/setup/generate-license"
template: "{installed_path}/template.LICENSE"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
default_output_file: "{project-root}/LICENSE"

# Web bundle configuration
web_bundle:
  name: "generate-license"
  description: "Gera arquivo LICENSE com copyright da Embrapa automaticamente"
  author: "BMad Embrapa I/O Module"
  version: "1.0.0"

  web_bundle_files:
    - "bmad/embrapa-io/workflows/setup/generate-license/workflow.yaml"
    - "bmad/embrapa-io/workflows/setup/generate-license/instructions.md"
    - "bmad/embrapa-io/workflows/setup/generate-license/template.LICENSE"
    - "bmad/embrapa-io/workflows/setup/generate-license/checklist.md"
