# Validate Compliance Workflow Configuration
category: "validate"

# Critical variables from config_source
config_source: "{project-root}/bmad/embrapa-io/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Workflow paths
installed_path: "{project-root}/bmad/embrapa-io/workflows/validate/validate-compliance"
template: false  # Action workflow - generates reports dynamically
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
validation_report_json: "{output_folder}/validation-report-{{project_name}}-{{date}}.json"
validation_report_md: "{output_folder}/compliance-summary-{{project_name}}-{{date}}.md"

# Web bundle configuration
web_bundle:
  name: "validate-compliance"
  description: "Validação completa de conformidade com a plataforma Embrapa I/O"
  author: "BMad Embrapa I/O Module"
  version: "2.0.0"

  web_bundle_files:
    - "bmad/embrapa-io/workflows/validate/validate-compliance/workflow.yaml"
    - "bmad/embrapa-io/workflows/validate/validate-compliance/instructions.md"
    - "bmad/embrapa-io/workflows/validate/validate-compliance/checklist.md"
    - "bmad/embrapa-io/knowledge/embrapa-io-fundamentals.md"
    - "bmad/embrapa-io/knowledge/embrapa-io-validation.md"
    - "bmad/embrapa-io/knowledge/embrapa-io-workflows.md"
    - "bmad/embrapa-io/knowledge/embrapa-io-deployment.md"
    - "bmad/embrapa-io/knowledge/embrapa-io-stacks.md"
    - "bmad/embrapa-io/knowledge/embrapa-io-integrations.md"
