# Generate .env.io Workflow Configuration
name: generate-env-io
description: "Gera arquivos .env.io e .env.io.example com variáveis da plataforma Embrapa I/O"
author: "BMad Embrapa I/O Module"
version: "1.0.0"

# Critical variables from config_source
config_source: "{project-root}/bmad/embrapa-io/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Workflow paths
installed_path: "{project-root}/bmad/embrapa-io/workflows/setup/generate-env-io"
template: "{installed_path}/template.env.io"
instructions: "{installed_path}/instructions.md"

# Output configuration
default_output_file: "{project-root}/.env.io"
example_output_file: "{project-root}/.env.io.example"

# Web bundle configuration
web_bundle:
  name: "generate-env-io"
  description: "Gera arquivos .env.io e .env.io.example com variáveis da plataforma Embrapa I/O"
  author: "BMad Embrapa I/O Module"
  version: "1.0.0"

  web_bundle_files:
    - "bmad/embrapa-io/workflows/setup/generate-env-io/workflow.yaml"
    - "bmad/embrapa-io/workflows/setup/generate-env-io/instructions.md"
    - "bmad/embrapa-io/workflows/setup/generate-env-io/template.env.io"
