# Generate .embrapa/settings.json Workflow Configuration
name: generate-settings-json
description: "Gera arquivo .embrapa/settings.json conforme com a plataforma Embrapa I/O"
author: "BMad Embrapa I/O Module"

# Critical variables from config_source
config_source: "{project-root}/bmad/embrapa-io/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Workflow paths
installed_path: "{project-root}/bmad/embrapa-io/workflows/setup/generate-settings-json"
template: "{installed_path}/template.settings.json"
instructions: "{installed_path}/instructions.md"

# Output configuration
default_output_file: "{project-root}/.embrapa/settings.json"

# Web bundle configuration
web_bundle:
  name: "generate-settings-json"
  description: "Gera arquivo .embrapa/settings.json conforme com a plataforma Embrapa I/O"
  author: "BMad Embrapa I/O Module"
  version: "1.0.0"

  web_bundle_files:
    - "bmad/embrapa-io/workflows/setup/generate-settings-json/workflow.yaml"
    - "bmad/embrapa-io/workflows/setup/generate-settings-json/instructions.md"
    - "bmad/embrapa-io/workflows/setup/generate-settings-json/template.settings.json"
    - "bmad/embrapa-io/workflows/setup/generate-settings-json/checklist.md"
    - "bmad/embrapa-io/templates/settings/settings-base.json"
    - "bmad/embrapa-io/templates/settings/settings-nodejs.json"
    - "bmad/embrapa-io/templates/settings/settings-frontend.json"
